import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type ModelType = {
  id?: number;
  title: string;
  color: string[];
  img: string;
};

export type GLTFResultType = GLTF & {
  nodes: {
    ttmRoLdJipiIOmf: THREE.Mesh;
    DjsDkGiopeiEJZK: THREE.Mesh;
    buRWvyqhBBgcJFo: THREE.Mesh;
    MrMmlCAsAxJpYqQ_0: THREE.Mesh;
    wqbHSzWaUxBCwxY_0: THREE.Mesh;
    QvGDcbDApaGssma: THREE.Mesh;
    vFwJFNASGvEHWhs: THREE.Mesh;
    evAxFwhaQUwXuua: THREE.Mesh;
    USxQiqZgxHbRvqB: THREE.Mesh;
    TvgBVmqNmSrFVfW: THREE.Mesh;
    GuYJryuYunhpphO: THREE.Mesh;
    pvdHknDTGDzVpwc: THREE.Mesh;
    CfghdUoyzvwzIum: THREE.Mesh;
    DjdhycfQYjKMDyn: THREE.Mesh;
    usFLmqcyrnltBUr: THREE.Mesh;
    xXDHkMplTIDAXLN: THREE.Mesh;
    vELORlCJixqPHsZ: THREE.Mesh;
    EbQGKrWAqhBHiMv: THREE.Mesh;
    EddVrWkqZTlvmci: THREE.Mesh;
    KSWlaxBcnPDpFCs: THREE.Mesh;
    TakBsdEjEytCAMK: THREE.Mesh;
    IykfmVvLplTsTEW: THREE.Mesh;
    wLfSXtbwRlBrwof: THREE.Mesh;
    WJwwVjsahIXbJpU: THREE.Mesh;
    YfrJNXgMvGOAfzz: THREE.Mesh;
    DCLCbjzqejuvsqH: THREE.Mesh;
    CdalkzDVnwgdEhS: THREE.Mesh;
    NtjcIgolNGgYlCg: THREE.Mesh;
    pXBNoLiaMwsDHRF: THREE.Mesh;
    IkoiNqATMVoZFKD: THREE.Mesh;
    rqgRAGHOwnuBypi: THREE.Mesh;
  };
  materials: {
    hUlRcbieVuIiOXG: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    dxCVrUCvYhjVxqy: THREE.MeshStandardMaterial;
    MHFGNLrDQbTNima: THREE.MeshStandardMaterial;
    kUhjpatHUvkBwfM: THREE.MeshStandardMaterial;
    RJoymvEsaIItifI: THREE.MeshStandardMaterial;
    KSIxMqttXxxmOYl: THREE.MeshStandardMaterial;
    mcPrzcBUcdqUybC: THREE.MeshStandardMaterial;
    pIhYLPqiSQOZTjn: THREE.MeshStandardMaterial;
    eShKpuMNVJTRrgg: THREE.MeshStandardMaterial;
    xdyiJLYTYRfJffH: THREE.MeshStandardMaterial;
    jpGaQNgTtEGkTfo: THREE.MeshStandardMaterial;
    ujsvqBWRMnqdwPx: THREE.MeshStandardMaterial;
    sxNzrmuTqVeaXdg: THREE.MeshStandardMaterial;
    pIJKfZsazmcpEiU: THREE.MeshStandardMaterial;
    zFdeDaGNRwzccye: THREE.MeshStandardMaterial;
    TBLSREBUyLMVtJa: THREE.MeshStandardMaterial;
    xNrofRCqOXXHVZt: THREE.MeshStandardMaterial;
    yQQySPTfbEJufve: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshStandardMaterial;
    oZRkkORNzkufnGD: THREE.MeshStandardMaterial;
    yhcAXNGcJWCqtIS: THREE.MeshStandardMaterial;
    bCgzXjHOanGdTFV: THREE.MeshStandardMaterial;
    vhaEJjZoqGtyLdo: THREE.MeshStandardMaterial;
    jlzuBkUzuJqgiAK: THREE.MeshStandardMaterial;
    PpwUTnTFZJXxCoE: THREE.MeshStandardMaterial;
    yiDkEwDSyEhavuP: THREE.MeshStandardMaterial;
    hiVunnLeAHkwGEo: THREE.MeshStandardMaterial;
    HGhEhpqSBZRnjHC: THREE.MeshStandardMaterial;
  };
};
